version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  jobs:
    install:
      - cargo install mdbook
    build:
      html:
        - "$(dirname $(which cargo))/mdbook" build book --dest-dir $READTHEDOCS_OUTPUT/html
